vich_uploader:
    db_driver: orm

    mappings:
        campaigns:
            uri_prefix: /images/campaigns
            upload_destination: '%kernel.project_dir%/public/images/campaigns'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
